name: Quality Gates
on: [pull_request]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Ban legacy storage
      - name: Ban local/sessionStorage
        run: |
          ! git grep -nE '\b(localStorage|sessionStorage)\b' -- ':!**/__tests__/**'

      # 2) Install deps (pnpm or npm)
      - name: Install deps
        run: |
          corepack enable || true
          pnpm install --frozen-lockfile || npm ci

      # 3) Run tests
      - name: Tests
        run: |
          pnpm test -- --run || npm test -- --run
        env:
          CI: true
